Repository thomashoneyman/purescript-halogen-hooks, pull requests merged in 2020-05, with the labels that each got.

#25 Support skipping evaluations when input is unchanged
  src/Halogen/Hooks/Component.purs
  src/Halogen/Hooks/Internal/Eval.purs
  test/Test/Hooks/UseMemo.purs
  test/Test/Setup/Eval.purs
Labels: enhancement

#29 Return a modify function from useState instead of a token
  README.md
  docs/01-Hooks-At-A-Glance.md
  docs/07-Hooks-API.md
  docs/08-Hooks-FAQ.md
  examples/Example/Halogen/Basic/Button.purs
  examples/Example/Halogen/Components/Button.purs
  examples/Example/Halogen/Components/Container.purs
  examples/Example/Halogen/ComponentsInputs/Container.purs
  examples/Example/Halogen/Effects/Random.purs
  examples/Example/Hooks/Components.purs
  examples/Example/Hooks/UseGet.purs
  examples/Example/Hooks/UseLocalStorage.purs
  examples/Example/Hooks/UseWindowWidth.purs
  examples/Example/Main.purs
  src/Halogen/Hooks.purs
  src/Halogen/Hooks/HookM.purs
  src/Halogen/Hooks/Internal/Eval.purs
  src/Halogen/Hooks/Internal/Types.purs
  src/Halogen/Hooks/Internal/UseHookF.purs
  src/Halogen/Hooks/Types.purs
  test/Test/Hooks/Bug5.purs
  test/Test/Hooks/UseEffect/UseLifecycleEffect.purs
  test/Test/Hooks/UseEffect/UseTickEffect.purs
  test/Test/Hooks/UseMemo.purs
  test/Test/Hooks/UseState.purs
  test/Test/Setup/Eval.purs
Labels: breaking change

#23 Refactor tests into Primitive and Complex folders
  test/Test/Hooks/Complex/Bug5.purs
  test/Test/Hooks/Primitive/UseEffect.purs
  test/Test/Hooks/Primitive/UseEffect/UseLifecycleEffect.purs
  test/Test/Hooks/Primitive/UseEffect/UseTickEffect.purs
  test/Test/Hooks/Primitive/UseMemo.purs
  test/Test/Hooks/Primitive/UseRef.purs
  test/Test/Hooks/Primitive/UseState.purs
  test/Test/Hooks/UseEffect.purs
  test/Test/Main.purs
Labels: internal

#33 Replace foldFree with substFree
  src/Halogen/Hooks/Component.purs
  src/Halogen/Hooks/Internal/Eval.purs
  test/Test/Setup/Eval.purs
Labels: internal
